# Catppuccin Mocha — kitty palette
# https://github.com/catppuccin/kitty

cursor_shape               beam
cursor_underline_thickness 1
window_padding_width       20

# Special
foreground #cdd6f4
background #1e1e2e

# Black
color0 #45475a
color8 #585b70

# Red
color1 #f38ba8
color9 #f38ba8

# Green
color2  #a6e3a1
color10 #a6e3a1

# Yellow
color3  #f9e2af
color11 #f9e2af

# Blue
color4  #89b4fa
color12 #89b4fa

# Magenta
color5  #f5c2e7
color13 #f5c2e7

# Cyan
color6  #94e2d5
color14 #94e2d5

# White
color7  #bac2de
color15 #a6adc8

# Cursor
cursor          #f5e0dc
cursor_text_color #1e1e2e

# Selection highlight
selection_foreground #1e1e2e
selection_background #f5e0dc

# URL underline
url_color #89b4fa

# Tab bar
active_tab_background   #a6e3a1
active_tab_foreground   #1e1e2e
inactive_tab_background #45475a
inactive_tab_foreground #cdd6f4
tab_bar_margin_color    #1e1e2e
